###
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "John",
    "email": "john@example.com"
}

###
GET http://localhost:3000/users

###
GET http://localhost:3000/users/1

###
DELETE http://localhost:3000/users/2

###
POST http://localhost:3000/posts
Content-Type: application/json

{
    "title": "Prismaの基本",
    "content": "リレーションショッピンの設定を確認中",
    "authorId": 1
}

###
POST http://localhost:3000/posts
Content-Type: application/json

{
    "title": "Prismaの基本2",
    "content": "Postテーブルへの新規データ作成を確認",
    "authorId": 1
}

###
GET http://localhost:3000/users